### ISSUE TITLE
Gain and offset steps are missing from sequence if set to zero

### ISSUE THREAD

**Issue by scottsousa** [linuxkidd/SharpCap-Eclipse-Sequencer#7]
Hi @linuxkidd ,

In #6 I've added a fix to account for an issue I ran into while testing the script today. The steps for gain and offset were not included in my generated sequencer script.

I think this should be a fairly straight forward merge. Let me know if you need any other details from me.

Thanks!

**Comment by linuxkidd** [comment]
Thanks for the catch and code fix!   I've merged it now.
